### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xracket#1]
In order to launch we should have:

- [x] Racket as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] at least 10 problems
- [x] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-racket.md`)
- [x] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [x] add track implementors and other designated nitpickers as mentors to the track
- [x] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by yurrriq** [comment]
:+1: for this! Will xracket be added to the lisp team?

**Comment by kytrinyx** [comment]
Good idea. Yepp, doing so now.

**Comment by arguello** [comment]
Cool. @yurrriq - would you mind checking my pr?

**Comment by arguello** [comment]
@kytrinyx - will you add @mbertheau to the team?

**Comment by kytrinyx** [comment]
Yepp, will do.

**Comment by kytrinyx** [comment]
Hey all--it looks like Racket is ready to go live. Is there anything holding us back?

**Comment by zenspider** [comment]
@kytrinyx Please close this?
